# -*- coding: utf-8 -*-
"""Insurance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ZpuaiOoOo9a3wWPIG5jH1T8Dh1gHnQA
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error,
    accuracy_score,
    confusion_matrix,
    classification_report
)

df = pd.read_csv("insurance.csv")

print(df.head())
print(df.info())

print("Missing Values")
print(df.isnull().sum())

df.drop_duplicates(inplace=True)

print("Shape:", df.shape)

print("\nAverage Age:", df['age'].mean())
print("Average BMI:", df['bmi'].mean())
print("Average Children:", df['children'].mean())
print("Average Charges:", df['charges'].mean())

print(df.describe())

plt.figure(figsize=(8,5))
sns.histplot(df['age'], kde=True)
plt.title("Age Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['bmi'], kde=True)
plt.title("BMI Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['charges'], kde=True)
plt.title("Insurance Charges Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x='age', y='charges', data=df)
plt.title("Age vs Charges")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x='bmi', y='charges', data=df)
plt.title("BMI vs Charges")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='smoker', y='charges', data=df)
plt.title("Smoker vs Charges")
plt.show()

plt.figure(figsize=(8,5))
sns.barplot(x='region', y='charges', data=df)
plt.title("Region Wise Charges")
plt.show()

df['sex'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)
plt.title("Gender Distribution")
plt.show()

df['smoker'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)
plt.title("Smoker Distribution")
plt.show()

le = LabelEncoder()

df['sex'] = le.fit_transform(df['sex'])
df['smoker'] = le.fit_transform(df['smoker'])
df['region'] = le.fit_transform(df['region'])

plt.figure(figsize=(10,6))
sns.heatmap(
    df.corr(),
    annot=True,
    cmap='coolwarm'
)
plt.title("Correlation Heatmap")
plt.show()

q1 = df['charges'].quantile(0.33)
q2 = df['charges'].quantile(0.66)

def classify_cost(x):

    if x <= q1:
        return "Low Cost"

    elif x <= q2:
        return "Medium Cost"

    else:
        return "High Cost"

df['risk_category'] = df['charges'].apply(classify_cost)

print(df['risk_category'].value_counts())

X = df[['age']]
y = df['charges']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

lr = LinearRegression()

lr.fit(X_train, y_train)

pred = lr.predict(X_test)

print("\nSIMPLE LINEAR REGRESSION")

print("R2:", r2_score(y_test, pred))
print("MAE:", mean_absolute_error(y_test, pred))
print("MSE:", mean_squared_error(y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred)))

X = df[['age', 'bmi', 'children', 'smoker']]
y = df['charges']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

mlr = LinearRegression()

mlr.fit(X_train, y_train)

pred2 = mlr.predict(X_test)

print("\nMULTIPLE LINEAR REGRESSION")

print("R2:", r2_score(y_test, pred2))
print("MAE:", mean_absolute_error(y_test, pred2))
print("MSE:", mean_squared_error(y_test, pred2))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred2)))

median_charge = df['charges'].median()

df['insurance_category'] = np.where(
    df['charges'] > median_charge,
    1,
    0
)

X = df[['age', 'bmi', 'children', 'smoker']]
y = df['insurance_category']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train, y_train)

pred3 = log_model.predict(X_test)

print("\nLOGISTIC REGRESSION")

print("Accuracy:",
      accuracy_score(y_test, pred3))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, pred3))

print("\nClassification Report")
print(classification_report(y_test, pred3))

import pandas as pd
import plotly.express as px

df = pd.read_csv("insurance.csv")

fig = px.histogram(
    df,
    x="charges",
    title="Insurance Charges Distribution"
)
fig.show()

fig = px.scatter(
    df,
    x="age",
    y="charges",
    color="smoker",
    title="Age vs Charges"
)
fig.show()

fig = px.scatter(
    df,
    x="bmi",
    y="charges",
    color="smoker",
    title="BMI vs Charges"
)
fig.show()

fig = px.box(
    df,
    x="smoker",
    y="charges",
    title="Smoker vs Charges"
)
fig.show()

fig = px.bar(
    df.groupby('region')['charges']
      .mean()
      .reset_index(),
    x='region',
    y='charges',
    title='Region Wise Charges'
)
fig.show()